services:
  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
    networks:
      - laravel-network
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"

  laravel:
    image: bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_myapp
      - DB_DATABASE=bitnami_myapp
    ports:
      - "8000:8000"
    networks:
      - laravel-network
    volumes:
      - ./laravel-ferreteria:/app
    restart: unless-stopped

networks:
  laravel-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
